#!/bin/sh
# 系统默认 shell 配置

export PATH=/usr/sbin:/usr/bin:/sbin:/bin
export HOME=/root
export PS1='\u@\h:\w\$ '
export TERM=linux

alias ll='ls -la'
alias la='ls -A'
alias l='ls -CF'
alias cls='clear'
alias reboot='echo "Use: echo b > /proc/sysrq-trigger 或 reboot -f"'
alias status='cat /proc/loadavg; free; ip addr show'
alias restart-net='/etc/init.d/S40network && /etc/init.d/S45firewall && /etc/init.d/S50dhcp'

echo ""
echo "  Welcome to Reasonix Router v1.0"
echo "  Type 'help' for available commands."
echo ""
